<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Version>0.0.0.8</Version>
    <Title>DSP在线升级算法库</Title>
    <Description>DSP在线升级算法库</Description>
    <Copyright>昆明光博科技有限公司</Copyright>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>

</Project>
